"""Generate docs/voice-commands.md from an aliases file.

Usage:
    python scripts/gen_commands.py [aliases.json] [docs/voice-commands.md]

The aliases file maps a spoken phrase to either a string (text sent to the
assistant as a prompt) or an object {"run": [...], "speak_output": bool}
(a command the listener runs locally, with no model turn). Phrases that do
the same thing are grouped into one row.
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
source = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "aliases.example.json"
target = Path(sys.argv[2]) if len(sys.argv) > 2 else ROOT / "docs" / "voice-commands.md"

# Plain-language meaning of each local action, keyed by the arguments that
# follow the script name. Unknown actions still appear, described by command.
MEANINGS = {
    "voice": "Switch the speaking voice to `{0}`.",
    "voices": "Read out the available voices.",
    "stop": "Cut off speech that is playing now and release the speech floor.",
    "volume up": "Raise the speech volume one step.",
    "volume down": "Lower the speech volume one step.",
    "disable": "Turn spoken replies off.",
    "enable": "Turn spoken replies back on.",
    "ping": "Do nothing. Proves the listener heard and matched the phrase; sends nothing to the assistant.",
    "gate on": "Arm the start-of-turn approval gate.",
    "gate off": "Disarm the start-of-turn approval gate.",
    "gate status": "Say whether the approval gate is armed.",
    "busy": "Say whether the assistant is working, waiting for approval, or idle.",
    "latency spoken": "Read out how long the last turn took at each stage.",
    "sound_check.mjs": "Read out microphone level and listener health.",
    "master_status.py": "Read out a status roll call across sessions.",
}


def describe(value):
    if isinstance(value, str):
        return "prompt", value, "Send this text to the assistant as a prompt."
    run = value["run"]
    script = Path(run[1]).name if len(run) > 1 else Path(run[0]).name
    rest = run[2:]
    key = " ".join(rest)
    shown = " ".join([script, *rest])
    if rest and rest[0] == "voice":
        meaning = MEANINGS["voice"].format(rest[1])
    else:
        meaning = MEANINGS.get(key) or MEANINGS.get(script) or "Run the command shown."
    if value.get("speak_output"):
        meaning += " The output is read aloud."
    return "local", shown, meaning


aliases = json.loads(source.read_text(encoding="utf-8"))
groups = {}
for phrase, value in aliases.items():
    kind, shown, meaning = describe(value)
    groups.setdefault((kind, shown, meaning), []).append(phrase)

lines = [
    "# Voice commands",
    "",
    f"Generated by `scripts/gen_commands.py` from `{source.name}`. Do not edit by hand.",
    "",
    f"{len(aliases)} phrases, {len(groups)} distinct actions. Say the wake phrase first,",
    'for example "hey claude, latency report".',
    "",
]
for kind, title, note in (
    ("local", "Run by the listener (no model turn)",
     "These never reach the assistant, so they cost no tokens and work while it is busy."),
    ("prompt", "Sent to the assistant as a prompt",
     "The phrase is replaced by the exact text shown and submitted as a normal message."),
):
    lines += [f"## {title}", "", note, "", "| Say | Runs or sends | What happens |", "|---|---|---|"]
    for (k, shown, meaning), phrases in groups.items():
        if k == kind:
            said = ", ".join(f'"{p}"' for p in phrases)
            lines.append(f"| {said} | `{shown}` | {meaning} |")
    lines.append("")

target.parent.mkdir(parents=True, exist_ok=True)
target.write_text("\n".join(lines), encoding="utf-8", newline="\n")
print(f"{len(aliases)} phrases, {len(groups)} actions -> {target}")
